Update proposal prioritization
ibriz/CPS pull request #97
Opened 2022-03-21 08:22 UTC by sdpisreddevil

Please check commits

2022-03-23 23:16 UTC, goldworm requested changes

2022-03-23 23:16 UTC, goldworm commented on cps_score/cps_score.py
> +        _not_voters = [addr for addr in _valid_preps_list + _voters_list if
Aren't _not_voters are those who are in _valid_preps_list but not in _voters_list?
It seems quite weird and not optimized but i'm not sure.
I think this code have some parts to optimize with dict but I couldn't fix it due to my short understanding.

2022-03-24 01:03 UTC, sdpisreddevil commented on cps_score/cps_score.py
> +        _not_voters = [addr for addr in _valid_preps_list + _voters_list if
Yeah, it's the list for [_valid_preps_list - _voters_list]

2022-03-24 05:15 UTC, goldworm commented on cps_score/cps_score.py
> +        _not_voters = [addr for addr in _valid_preps_list + _voters_list if
Ok. then i'll suggest new update for this.

2022-03-24 07:58 UTC, goldworm-icon approved these changes

2022-03-25 02:41 UTC, goldworm approved these changes

2022-03-25 04:42 UTC, merged